### ISSUE TITLE
Includes in parent folders are not resolved

### ISSUE THREAD

**Issue by DarrenTheDev** [coen-hyde/gulp-cog#3]
Useful plugin. However if the included file is in a directory above the file with the comment it isn't resolved. 

A common use case for this would be:
//= require ../bower_components/whatever

Would be a nice feature for this plugin to support.

**Comment by coen-hyde** [comment]
@DarrenTheDev Sorry for the late reply. That's because gulp-cog only searches for files currently in the stream (i.e it doesn't look for files on the file system. You could quite easily import files from the directory above though. Add the files from bower_components to the stream, rename them by prepending bower_components to the path, then source them in your file with //= require bower_components/whatever
